# Site settings
ref: CSCC09
title: Programming on the Web
edition: Spring 2019
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.github.io/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/mail.utoronto.ca/spring2019/cscc09
feedback: https://goo.gl/forms/nIB52HdQeYiWjsBZ2

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: TBD (or by appointment)
  location: IC-346
  contact: Piazza only (no mail)
  role: LEC

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: TBD
      role:  TBD
      contact: "&#106;&#97;&#110;&#97;&#46;&#103;&#97;&#98;&#108;&#97;&#110;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: IC-400

  
timings:
    - section: LEC01 
      time: Monday 11:00-12:00
      location: MW 160 
    - section: 
      time: Friday 11:00-13:00
      location: HW 214 
    # - section: LEC02
    #   time: Monday 13:00-15:00
    #   location: IC 220
    # - section:
    #   time: Friday 14:00-15:00
    #   location: MV 160
    # - section: PRA01
    #   time: Monday 9:00-11:00
    #   location: BV 473
    # - section: PRA02
    #   time: Monday 15:00-17:00
    #   location: BV 473
    # - section: PRA03
    #   time: Friday 9:00-11:00
    #   location: BV 473
    # - section: PRA04
    #   time: Thursday 18:00-20:00
    #   location: BV 473
        
first: 20190107