# Site settings
ref: CSCC09
title: Programming on the Web
edition: Spring 2019
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.github.io/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/mail.utoronto.ca/spring2019/cscc09
feedback: https://goo.gl/forms/nIB52HdQeYiWjsBZ2

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: TBD (or by appointment)
  location: IC-346
  contact: Piazza only (no mail)
  role: LEC

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Murielle Butchuen
      role:  TBD
      contact: "&#109;&#117;&#114;&#105;&#101;&#108;&#108;&#101;&#46;&#98;&#117;&#116;&#99;&#104;&#117;&#101;&#110;&#116;&#97;&#109;&#110;&#111;&#117;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: IC-400
    - name: Sai Oduri
      role:  TBD
      contact: "&#115;&#97;&#105;&#46;&#111;&#100;&#117;&#114;&#105;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: IC-400
    - name: Vino Tharmalenkam
      role:  TBD
      contact: "&#118;&#105;&#110;&#111;&#46;&#116;&#104;&#97;&#114;&#109;&#97;&#108;&#101;&#110;&#107;&#97;&#109;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: IC-400
    - name: Bekzod Tursunov
      role:  TBD
      contact: "&#98;&#101;&#107;&#122;&#111;&#100;&#46;&#116;&#117;&#114;&#115;&#117;&#110;&#111;&#118;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: IC-400
    - name: Samuel Zhou
      role:  TBD
      contact: "&#115;&#97;&#109;&#117;&#101;&#108;&#46;&#122;&#104;&#111;&#117;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: IC-400
  
timings:
    - section: LEC01 
      time: Tuesday 12:00-14:00
      location: SW-319
    - section: LEC02
      time: Friday 13:00-15:00
      location: MW-160
    - section: PRA01
      time: Monday 9:00-11:00
      location: BV-473
    - section: PRA02
      time: Monday 15:00-17:00
      location: BV-473
    - section: PRA03
      time: Friday 9:00-11:00
      location: BV-473
    - section: PRA04
      time: Friday 11:00-13:00
      location: BV-473
    - section: PRA05
      time: Tuesday 10:00-12:00
      location: BV-473
        
first: 20190107